name: BotPractice
version: '${project.version}'
main: com.njdge.botpractice.Main
api-version: '1.8.8'
commands:
  bp:
    description: start a game
    usage: /bp <value>
    aliases: [ bp ]
  mw:
    description: start a game
    usage: /mw tp <world>
    aliases: [ multiworld ]
  duel:
    description: start a game
    usage: /duel
depend: [Citizens]
